import type { Metadata } from "next";
import { JsonLd, breadcrumbSchema, faqSchema } from "@/components/Schema";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { SectionHead } from "@/components/SectionHead";
import { FAQ } from "@/components/ServicePage";
import { CtaBand } from "@/components/CtaBand";
import { DataTable } from "@/components/DataTable";
import { TextLink } from "@/components/v2";
import { REFUND_TIERS, money, premiumRange } from "@/lib/lmi-model";
import { pmt } from "@/lib/loan-model";
import { Calculator } from "./Calculator";

// Existing slug carried 1:1. "lmi calculator" 4,739/mo at KD 10 - a DR-14
// site holds #7, so this is winnable. SERP union: estimator (Helia/Lendi
// have it) + avoid-LMI strategy (nobody pairs it).

const PATH = "/lenders-mortgage-insurance-calculator";

export const metadata: Metadata = {
  title: { absolute: "LMI Calculator | Estimate Lenders Mortgage Insurance + How to Avoid It" },
  description:
    "Estimate your lenders mortgage insurance from property value and deposit (indicative premiums by LVR), and the four legitimate ways to avoid LMI entirely: the First Home Guarantee, guarantors, professional waivers and the 80% line.",
  alternates: { canonical: PATH },
};

// Both tables are generated by lib/lmi-model.ts and lib/loan-model.ts, the
// same models the estimator above runs. CAP_RATE and CAP_TERM are modelling
// assumptions for the capitalisation example, not rates on offer.
const TABLE_LOANS = [300_000, 500_000, 750_000, 950_000];
const TABLE_LVRS = [85, 90, 95];
const PREMIUMS = [5_000, 10_000, 15_000, 20_000];
const CAP_RATE = 6.0;
const CAP_TERM = 30;

const FAQS = [
  { q: "What is lenders mortgage insurance?", a: "LMI is a one-off insurance premium charged when you borrow more than 80% of a property's value. It protects the lender if you default, not you, and it's usually added to your loan, so you pay interest on it for the life of the loan." },
  { q: "How much is LMI on a $600,000 house with 10% deposit?", a: "A $540,000 loan at 90% LVR typically attracts an LMI premium somewhere around $8,000-$12,000 depending on insurer and lender. The calculator above brackets your exact numbers, and the avoid-LMI paths below it are often worth more than shopping the premium." },
  { q: "Can LMI be added to the loan?", a: "Usually yes. Most lenders capitalise the premium into the loan so you don't pay cash upfront. It's convenient but means paying interest on the premium for up to 30 years; the true cost is meaningfully higher than the sticker price." },
  { q: "How do I avoid paying LMI?", a: "Four real paths: get to a 20% deposit (or 80% LVR); use the First Home Guarantee if you're an eligible first home buyer (5% deposit, no LMI); use a family guarantor to bring effective LVR to 80%; or qualify for a professional LMI waiver: some lenders waive it to 90% LVR for doctors, lawyers, accountants and other professions." },
  { q: "Is LMI ever worth paying?", a: "Sometimes, honestly, yes. If prices in your target area are rising faster than you can save the next 10% of deposit, paying LMI to buy years earlier can be the cheaper mistake. It's a numbers comparison, one a broker can run with you in minutes." },
  { q: "Is LMI refundable if I refinance or sell?", a: "Only in a narrow window, and only sometimes. Helia, the largest LMI provider in Australia, publishes a partial refund of up to 40% of the premium where the loan is discharged within 12 months and up to 20% between 12 and 24 months, with nothing after that and nothing where the loan fell into arrears. Some policies trade the refund right away for a larger upfront discount, so it is not universal. Check the certificate of insurance for your loan and ask your lender, because the refund is claimed through them, not from the insurer directly." },
  { q: "Is LMI transferable to a new lender?", a: "No. The policy belongs to the lender, not to you, so refinancing above 80% LVR means a fresh premium at the new lender rather than a transfer of the old one. That is the single strongest argument for getting the lender choice right the first time when you are buying with a small deposit, and for waiting until your LVR is under 80% before refinancing if you can." },
  { q: "Is LMI tax deductible?", a: "Not for an owner-occupied home. For an investment property it is treated by the ATO as a borrowing expense, which means it is claimed over five years or the term of the loan, whichever is shorter, rather than all in the first year. If total borrowing expenses are $100 or less they can be claimed in full immediately, and if the loan is repaid early the remaining balance can be claimed in that year. Confirm the treatment with your accountant, and see ato.gov.au for the current rule." },
  { q: "Does LMI protect me if I can't make repayments?", a: "No, and this is the most common misunderstanding on the subject. LMI covers the lender's loss if the property is sold for less than the outstanding debt. If that happens, the insurer pays the lender and can then pursue you for the shortfall it paid out. The cover you buy for yourself is a different product entirely: income protection, life or mortgage protection insurance." },
];

const CRUMBS = [
  { name: "Home", path: "/" },
  { name: "LMI Calculator", path: PATH },
];

function rangeCell(loan: number, lvr: number): string {
  const r = premiumRange(loan, lvr);
  return r ? `${money(r[0])} to ${money(r[1])}` : "$0";
}

export default function Page() {
  // Cost of carrying a capitalised premium: the monthly cost per dollar of
  // premium, from the same amortisation the repayments calculator runs.
  const carryMultiple = pmt(1, CAP_RATE, CAP_TERM) * CAP_TERM * 12;
  return (
    <main>
      <JsonLd
        data={[
          {
            "@context": "https://schema.org",
            "@type": "WebApplication",
            name: "LINK Advance LMI Calculator",
            url: `https://linkadvance.com.au${PATH}`,
            applicationCategory: "FinanceApplication",
            operatingSystem: "Web",
            offers: { "@type": "Offer", price: 0, priceCurrency: "AUD" },
          },
          faqSchema(FAQS),
          breadcrumbSchema(CRUMBS),
        ]}
      />
      <Breadcrumbs crumbs={CRUMBS} />
      <section className="container-x pb-16 pt-10 sm:pt-14">
        <div className="max-w-3xl">
          <SectionHead
            as="h1"
            eyebrow="No email wall"
            title="LMI calculator, and the four ways to not pay it."
            mark="not pay it."
            intro="Enter your property value and deposit for an indicative lenders mortgage insurance estimate, then see whether the First Home Guarantee, a guarantor or a professional waiver makes the premium disappear entirely."
            accent
          />
        </div>
        <div className="mt-10">
          <Calculator />
        </div>
      </section>
      <section className="border-y border-ink/10 bg-neutral-50 py-20">
        <div className="container-x max-w-3xl">
          <h2 className="font-display text-[34px] font-normal leading-[1.15] tracking-tight text-ink sm:text-[44px]">
            What LMI costs, by loan size and deposit.
          </h2>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            Indicative premium ranges, modelled on published insurer tables (the exact figure
            varies by lender and insurer). The pattern to notice: the premium doesn&apos;t
            climb gently with your LVR, it jumps in bands, so a few thousand dollars more
            deposit at a band edge can save five figures.
          </p>
          <div className="mt-8">
            <DataTable
              caption="Indicative lenders mortgage insurance premium ranges by loan amount and loan-to-value ratio"
              head={["Loan amount", ...TABLE_LVRS.map((l) => `${l}% LVR`)]}
              rows={TABLE_LOANS.map((L) => [money(L), ...TABLE_LVRS.map((l) => rangeCell(L, l))])}
              note="Same model the calculator above runs. At 80% LVR or below the premium is zero. Premiums are usually capitalised into the loan, so you pay interest on them too."
            />
          </div>
          <p className="mt-6 text-lg leading-[1.4] text-ink/80">
            Before accepting any figure in this table, check the escape routes: the{" "}
            <TextLink href="/first-home-guarantee">First Home Guarantee</TextLink> (5% deposit, no
            LMI, no longer income-capped), a family guarantor, or a professional waiver if your
            occupation qualifies. For a $500,000 loan at 90% LVR, any one of those is worth{" "}
            {rangeCell(500_000, 90)}.
          </p>
        </div>
      </section>

      <section className="py-20">
        <div className="container-x max-w-3xl">
          <h2 className="font-display text-[34px] font-normal leading-[1.15] tracking-tight text-ink sm:text-[44px]">
            Capitalise the premium, or pay it up front?
          </h2>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            Almost everyone capitalises: the premium is added to the loan so it never leaves your
            bank account on settlement day. What nobody says out loud is that a capitalised
            premium is borrowed money, priced like the rest of the loan and repaid over the same
            term. Carried the full {CAP_TERM} years at an illustrative {CAP_RATE}% (a modelling
            rate, not a rate on offer), every dollar of premium costs about{" "}
            ${carryMultiple.toFixed(2)}.
          </p>
          <div className="mt-8">
            <DataTable
              caption="True cost of capitalising a lenders mortgage insurance premium over 30 years"
              head={["Premium", "Added to repayments", "Total repaid over 30 years", "Extra interest"]}
              rows={PREMIUMS.map((p) => [
                money(p),
                `${money(pmt(p, CAP_RATE, CAP_TERM))}/mo`,
                money(p * carryMultiple),
                money(p * carryMultiple - p),
              ])}
              note={`Modelled at ${CAP_RATE}% held constant over ${CAP_TERM} years, using the same amortisation as the repayments calculator. Most people do not hold a loan for 30 years, so treat this as the ceiling on the cost rather than the expected cost.`}
            />
          </div>
          <p className="mt-6 text-lg leading-[1.4] text-ink/80">
            Three things follow from the table. Paying the premium in cash is genuinely cheaper
            if you have the cash spare after settlement, but almost nobody does, and running your
            buffer to zero to save interest is a poor trade. Capitalising is usually allowed to
            take the loan slightly above the lender&apos;s maximum LVR, which is why a 95% LVR
            loan can settle at 96% or 97% of value once the premium is on top. And the real
            answer is neither: if you can attack the balance afterwards, the premium behaves like
            any other dollar of debt, so the{" "}
            <TextLink href="/home-loan-repayment-calculator">
              extra repayment and offset numbers
            </TextLink>{" "}
            apply to it directly.
          </p>
        </div>
      </section>

      <section className="border-y border-ink/10 bg-neutral-50 py-20">
        <div className="container-x max-w-3xl">
          <h2 className="font-display text-[34px] font-normal leading-[1.15] tracking-tight text-ink sm:text-[44px]">
            Is LMI refundable, and can you take it with you?
          </h2>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            Two questions that decide whether a small-deposit purchase is expensive or very
            expensive, and both answers are narrower than people hope.
          </p>
          <div className="mt-8">
            <DataTable
              caption="Indicative lenders mortgage insurance partial refund windows"
              head={["When the loan is discharged", "Typical refund"]}
              rows={REFUND_TIERS.map((t) => [t.window, t.share])}
              note="Refund positions published by Helia, Australia's largest LMI provider, as at August 2026. Refunds are not paid where the loan was in arrears, and some policies trade the refund entitlement for a larger upfront premium discount. Your certificate of insurance governs, and any claim goes through your lender."
            />
          </div>
          <p className="mt-6 text-lg leading-[1.4] text-ink/80">
            <strong className="text-ink">Refunds are a two-year window, at best.</strong> Sell or
            refinance in the first year and a partial refund may be available; after two years
            there is nothing. This matters most to people who take a high-LVR loan intending to
            refinance quickly, because the plan quietly stops paying for itself the moment the
            window closes.
          </p>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            <strong className="text-ink">The policy is not yours and does not move.</strong> LMI
            insures the lender, so when you refinance you are not transferring cover, you are
            leaving it behind. If the new loan is still above 80% LVR, the new lender charges a
            fresh premium. The practical rule: with a deposit under 20%, get the lender choice
            right at purchase, then leave the loan alone until either the balance has fallen or
            the property has risen enough to clear 80%, and only then look at{" "}
            <TextLink href="/refinancing-brisbane">refinancing</TextLink>. Working out where your
            LVR actually sits today is the first thing the{" "}
            <TextLink href="/home-loan-health-check">home loan health check</TextLink> asks you.
          </p>
        </div>
      </section>

      <section className="py-20">
        <div className="container-x max-w-3xl">
          <h2 className="font-display text-[34px] font-normal leading-[1.15] tracking-tight text-ink sm:text-[44px]">
            When paying LMI is the right call.
          </h2>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            The honest position is that LMI is sometimes the cheaper mistake. A worked example
            with the assumption stated openly, because the answer depends entirely on it.
          </p>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            Say the target is a $600,000 home and you have $60,000 saved. Buy now at 90% LVR and
            the loan is $540,000 with a premium somewhere in the{" "}
            {rangeCell(540_000, 90)} range. Wait instead, and to reach a 20% deposit you need
            $120,000, so at $2,500 a month of saving that is 24 months away. Now assume prices in
            your suburb rise 5% a year (an assumption, not a forecast): the same house is $661,500
            in two years and 20% of it is $132,300, so the target moved $12,300 further away while
            you were saving toward it. You also paid two more years of rent, and you own the house
            two years later.
          </p>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            Run the same arithmetic with prices flat and the answer flips: waiting costs you
            nothing but time, and you save the entire premium. Run it with prices falling and
            waiting is clearly right, because a 90% LVR loan leaves almost no equity buffer and a
            modest fall puts you underwater, unable to refinance and unable to sell without
            writing a cheque. That is the genuine downside of LMI lending and it does not get
            said often enough.
          </p>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            Before you accept the trade at all, exhaust the no-cost options. Eligible first home
            buyers can use the{" "}
            <TextLink href="/first-home-guarantee">First Home Guarantee</TextLink> for a 5%
            deposit with no LMI at all, which beats every version of this calculation. Some
            professions have{" "}
            <TextLink href="/home-loans-for-doctors">LMI waivers to 90% LVR</TextLink> at
            particular lenders. A family member with equity can act as a guarantor, and our note
            on{" "}
            <TextLink href="/blog/home-loans/guarantor-loans-whats-the-go">
              what a guarantor is actually signing up for
            </TextLink>{" "}
            is worth reading before you ask them. And in Queensland the duty side of the ledger
            may already have moved in your favour: check the{" "}
            <TextLink href="/stamp-duty-calculator-qld">stamp duty calculator</TextLink> and the{" "}
            <TextLink href="/first-home-buyers-grant">$30,000 grant</TextLink>, because money you
            do not hand to the government is deposit you did not have to save.
          </p>
        </div>
      </section>

      <section className="border-y border-ink/10 bg-neutral-50 py-20">
        <div className="container-x max-w-3xl">
          <h2 className="font-display text-[34px] font-normal leading-[1.15] tracking-tight text-ink sm:text-[44px]">
            What LMI is not.
          </h2>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            LMI is not insurance for you, and it is not mortgage protection insurance or the
            building insurance your lender requires at settlement. The premium buys the lender
            protection and buys you access to a loan you could not otherwise get; only the second
            of those is a benefit to the borrower. If protecting your household against the loan
            is what you are actually trying to do, that is an insurance conversation and a
            different professional.
          </p>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            One last practical note: the premium is calculated on the loan amount and the LVR
            together, and the LVR uses the lender&apos;s valuation, not your contract price. A
            valuation that comes in under contract pushes the LVR up and the premium with it, and
            it is one of the more common reasons a settlement figure changes late. Running your
            numbers across{" "}
            <TextLink href="/borrowing-power-calculator">borrowing power</TextLink> and the rest
            of the <TextLink href="/calculators">calculators and checks</TextLink> before you bid
            leaves room for that.
          </p>
        </div>
      </section>

      <FAQ
        title="Frequently asked questions."
        faqs={FAQS}
        related={[
          { label: "First Home Guarantee", href: "/first-home-guarantee" },
          { label: "Borrowing power estimator", href: "/borrowing-power-calculator" },
          { label: "First home buyer loans", href: "/first-home-buyers-loan" },
          { label: "All calculators and checks", href: "/calculators" },
        ]}
      />
      <CtaBand
        heading="Before you pay LMI, spend five minutes not paying it."
        intro="A broker checks the Guarantee, guarantor and waiver paths against your numbers."
        subject="LMI calculator"
      />
    </main>
  );
}
