import type { Metadata } from "next";
import { JsonLd, breadcrumbSchema, faqSchema } from "@/components/Schema";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { SectionHead } from "@/components/SectionHead";
import { FAQ } from "@/components/ServicePage";
import { CtaBand } from "@/components/CtaBand";
import { DataTable } from "@/components/DataTable";
import { TextLink } from "@/components/v2";
import {
  extraRepaymentEffect,
  ioPayment,
  money,
  pmt,
  totalInterest,
} from "@/lib/loan-model";
import { Calculator } from "./Calculator";

// "mortgage repayment calculator" 78k/mo and "home loan repayment
// calculator" 34.5k/mo are KD 57-59 head terms owned by banks - this page
// plays for the long tail and for conversion, not the head. The stress-test
// line and extra-repayment model are the differentiators.

const PATH = "/home-loan-repayment-calculator";

export const metadata: Metadata = {
  title: { absolute: "Home Loan Repayment Calculator | Weekly, Fortnightly, Monthly + Stress Test" },
  description:
    "Calculate home loan repayments at any rate and term (monthly, fortnightly and weekly), plus the +3% stress test lenders actually apply and what extra repayments save. Free, on screen, no email wall.",
  alternates: { canonical: PATH },
};

// Everything below is generated by lib/loan-model.ts, the same amortisation
// the calculator above runs. EXAMPLE_RATE is a modelling assumption used to
// make the worked examples checkable, not a rate on offer.
const LOANS = [400_000, 500_000, 600_000, 700_000, 800_000, 1_000_000];
const RATES = [5.0, 5.5, 5.9, 6.5, 7.0];
const EXAMPLE_LOAN = 600_000;
const EXAMPLE_RATE = 6.0;
const EXAMPLE_TERM = 30;
const EXTRAS = [100, 200, 300, 500, 1_000];
const IO_YEARS = 5;

const FAQS = [
  { q: "How are home loan repayments calculated?", a: "Principal-and-interest repayments use an amortisation formula: each payment covers the month's interest on the remaining balance plus some principal, so early payments are interest-heavy and later ones principal-heavy. The calculator applies the standard formula lenders use." },
  { q: "Why do lenders assess me at a higher rate than I'll pay?", a: "APRA requires lenders to test that you could still afford repayments if rates rose: the serviceability buffer, currently around 3 percentage points above your actual rate. That stressed figure, not the advertised repayment, is what decides your borrowing power." },
  { q: "Do fortnightly repayments really save interest?", a: "Paying half your monthly amount fortnightly sneaks in one extra month's payment per year (26 halves = 13 months), which genuinely shortens the loan. The effect in this calculator's extra-repayment field: roughly one-twelfth of your monthly repayment as 'extra'. The trap is that some lenders calculate a 'true fortnightly' amount instead (the monthly figure times 12, divided by 26), which pays exactly the same total each year and saves nothing." },
  { q: "What difference do extra repayments make?", a: "On a typical 30-year loan, even a few hundred dollars extra per month removes years from the term and five figures from the interest. The calculator shows your exact numbers. An offset account achieves the same effect while keeping the cash accessible." },
  { q: "How much are repayments on a $500,000 home loan?", a: `Over 30 years, principal and interest, a $500,000 loan costs ${money(pmt(500_000, 5.5, 30))} a month at 5.5%, ${money(pmt(500_000, 6.0, 30))} at 6.0% and ${money(pmt(500_000, 6.5, 30))} at 6.5%. Every half a percentage point is worth roughly $160 a month on a loan that size, which is the whole argument for reviewing the rate annually rather than the loan.` },
  { q: "Is an offset account better than making extra repayments?", a: "In interest terms they are close to identical: a dollar in a full offset account reduces the interest-bearing balance exactly like a dollar of extra repayment. The differences are practical. Offset money stays yours and can be withdrawn without asking; extra repayments have to be redrawn, and lenders can restrict redraw. For investors the tax treatment matters more: redrawing from a loan can change the purpose of the borrowing and affect deductibility, while drawing on your own offset savings does not. Offsets usually sit inside a package with an annual fee, so if the balance you keep is small the fee can outweigh the saving." },
  { q: "What is the difference between principal and interest and interest only?", a: `Principal and interest pays down the debt from day one. Interest only pays the lender's interest and nothing else, so the balance is unchanged when the term ends. On a ${money(EXAMPLE_LOAN)} loan at an illustrative ${EXAMPLE_RATE}%, interest only is ${money(ioPayment(EXAMPLE_LOAN, EXAMPLE_RATE))} a month against ${money(pmt(EXAMPLE_LOAN, EXAMPLE_RATE, EXAMPLE_TERM))} for principal and interest. The catch arrives later: after a 5-year interest-only period the same debt has to be repaid over the remaining 25 years, so the repayment jumps to ${money(pmt(EXAMPLE_LOAN, EXAMPLE_RATE, EXAMPLE_TERM - IO_YEARS))}, and total interest over the 30 years rises by about ${money(ioPayment(EXAMPLE_LOAN, EXAMPLE_RATE) * IO_YEARS * 12 + totalInterest(EXAMPLE_LOAN, EXAMPLE_RATE, EXAMPLE_TERM - IO_YEARS) - totalInterest(EXAMPLE_LOAN, EXAMPLE_RATE, EXAMPLE_TERM))}.` },
  { q: "Can I change my repayments from monthly to fortnightly?", a: "Usually yes, and it is a phone call or an app setting rather than a refinance. Ask the lender to confirm which method they use: half the monthly amount paid 26 times a year adds a thirteenth monthly payment and shortens the loan, while a recalculated 'true fortnightly' amount does not. Also check whether the loan caps extra repayments, which fixed-rate loans commonly do." },
];

const CRUMBS = [
  { name: "Home", path: "/" },
  { name: "Repayments Calculator", path: PATH },
];

export default function Page() {
  const monthly = pmt(EXAMPLE_LOAN, EXAMPLE_RATE, EXAMPLE_TERM);
  const baseInterest = totalInterest(EXAMPLE_LOAN, EXAMPLE_RATE, EXAMPLE_TERM);
  const io = ioPayment(EXAMPLE_LOAN, EXAMPLE_RATE);
  const afterIo = pmt(EXAMPLE_LOAN, EXAMPLE_RATE, EXAMPLE_TERM - IO_YEARS);
  const ioTotalInterest = io * IO_YEARS * 12 + totalInterest(EXAMPLE_LOAN, EXAMPLE_RATE, EXAMPLE_TERM - IO_YEARS);
  const fortnightlyEffect = extraRepaymentEffect(EXAMPLE_LOAN, EXAMPLE_RATE, EXAMPLE_TERM, monthly / 12);

  return (
    <main>
      <JsonLd
        data={[
          {
            "@context": "https://schema.org",
            "@type": "WebApplication",
            name: "LINK Advance Home Loan Repayment Calculator",
            url: `https://linkadvance.com.au${PATH}`,
            applicationCategory: "FinanceApplication",
            operatingSystem: "Web",
            offers: { "@type": "Offer", price: 0, priceCurrency: "AUD" },
          },
          faqSchema(FAQS),
          breadcrumbSchema(CRUMBS),
        ]}
      />
      <Breadcrumbs crumbs={CRUMBS} />
      <section className="container-x pb-16 pt-10 sm:pt-14">
        <div className="max-w-3xl">
          <SectionHead
            as="h1"
            eyebrow="Free tool · no email wall"
            title="Home loan repayment calculator, with the stress test banks apply."
            mark="stress test banks apply."
            intro="Monthly, fortnightly and weekly repayments at your rate and term, the total interest over the loan, what the +3% assessment buffer does to the numbers, and what extra repayments actually save."
            accent
          />
        </div>
        <div className="mt-10">
          <Calculator />
        </div>
      </section>
      {/* The pre-computed table: same formula the calculator runs, so the
          page carries indexable answers, not just an interactive widget */}
      <section className="border-y border-ink/10 bg-neutral-50 py-20">
        <div className="container-x max-w-3xl">
          <h2 className="font-display text-[34px] font-normal leading-[1.15] tracking-tight text-ink sm:text-[44px]">
            Monthly repayments at a glance.
          </h2>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            Principal and interest over 30 years, by loan size and rate. Run your exact
            numbers in the calculator above; these are the reference points people ask about
            most.
          </p>
          <div className="mt-8">
            <DataTable
              caption="Monthly principal and interest repayments over 30 years by loan amount and interest rate"
              head={["Loan amount", ...RATES.map((r) => `${r.toFixed(1)}%`)]}
              rows={LOANS.map((L) => [money(L), ...RATES.map((r) => money(pmt(L, r, 30)))])}
              note="Principal and interest, 30-year term, standard amortisation, generated by the same model the calculator runs. The rate columns are modelling points, not rates on offer. Indicative only: your rate, fees and structure change the figure, and lenders assess you at roughly 3 percentage points above the rate you pay."
            />
          </div>
          <p className="mt-6 text-lg leading-[1.4] text-ink/80">
            Two readings worth taking from the table: the difference between 5.5% and 6.5% on
            a $600,000 loan is {money(pmt(600_000, 6.5, 30) - pmt(600_000, 5.5, 30))} a month
            ({money((pmt(600_000, 6.5, 30) - pmt(600_000, 5.5, 30)) * 12)} a year), which is why
            the yearly repricing call matters. And a lender assessing you at the 3% buffer reads
            your $600,000 loan at roughly the 8.9% row that isn&apos;t on this table:{" "}
            {money(pmt(600_000, 8.9, 30))} a month. That gap between what you&apos;d pay and what
            you must prove you could pay is the borrowing power question, and the{" "}
            <TextLink href="/borrowing-power-calculator">borrowing power estimator</TextLink>{" "}
            runs it.
          </p>
        </div>
      </section>

      <section className="py-20">
        <div className="container-x max-w-3xl">
          <h2 className="font-display text-[34px] font-normal leading-[1.15] tracking-tight text-ink sm:text-[44px]">
            What extra repayments actually buy.
          </h2>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            A worked example on a {money(EXAMPLE_LOAN)} loan over {EXAMPLE_TERM} years at an
            illustrative {EXAMPLE_RATE}% (a modelling rate, not a rate on offer). The minimum
            repayment is {money(monthly)} a month and the interest over the full term is{" "}
            {money(baseInterest)}. Every row below is that same loan with one extra amount paid
            each month from day one.
          </p>
          <div className="mt-8">
            <DataTable
              caption="Effect of extra monthly repayments on a $600,000 home loan over 30 years"
              head={["Extra per month", "Loan paid off in", "Years saved", "Interest saved"]}
              rows={EXTRAS.map((ex) => {
                const e = extraRepaymentEffect(EXAMPLE_LOAN, EXAMPLE_RATE, EXAMPLE_TERM, ex);
                return [
                  money(ex),
                  `${(EXAMPLE_TERM - e.yearsSaved).toFixed(1)} years`,
                  e.yearsSaved.toFixed(1),
                  money(e.interestSaved),
                ];
              })}
              note={`Modelled at ${EXAMPLE_RATE}% held constant for the whole term, generated by the same amortisation the calculator above runs. Rates move, so treat this as the shape of the effect rather than a forecast. Fixed-rate loans usually cap extra repayments, and some loans charge for early repayment in full.`}
            />
          </div>
          <p className="mt-6 text-lg leading-[1.4] text-ink/80">
            The first {money(100)} a month is the hardest-working money in the table:{" "}
            {money(extraRepaymentEffect(EXAMPLE_LOAN, EXAMPLE_RATE, EXAMPLE_TERM, 100).interestSaved)} of
            interest saved, because it attacks the balance in the years when the balance is
            largest. Each additional {money(100)} saves a little less than the one before, and by{" "}
            {money(1_000)} a month you are buying{" "}
            {extraRepaymentEffect(EXAMPLE_LOAN, EXAMPLE_RATE, EXAMPLE_TERM, 1_000).yearsSaved.toFixed(1)} years
            off the term. Timing carries the same lesson: the identical dollars paid in year
            twenty save a fraction of what they save in year one, which is why the argument for
            starting small and early beats the argument for waiting until you can do it properly.
          </p>
        </div>
      </section>

      <section className="border-y border-ink/10 bg-neutral-50 py-20">
        <div className="container-x max-w-3xl">
          <h2 className="font-display text-[34px] font-normal leading-[1.15] tracking-tight text-ink sm:text-[44px]">
            Offset account, or extra repayments?
          </h2>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            In pure interest terms they do the same job. A full offset account is a transaction
            account linked to the loan, and the balance in it is subtracted from the loan balance
            before interest is calculated, so {money(30_000)} sitting in an offset against the
            {" "}{money(EXAMPLE_LOAN)} loan above saves{" "}
            {money((30_000 * EXAMPLE_RATE) / 100)} of interest in the first year, exactly as
            {money(30_000)} of extra repayment would.
          </p>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            The differences are all practical, and they matter more than the arithmetic.
          </p>
          <ul className="mt-5 space-y-4 text-lg leading-[1.4] text-ink/80">
            <li>
              <strong className="text-ink">Access.</strong> Offset money is yours, in a normal
              account, withdrawable at an ATM. Extra repayments sit inside the loan and come back
              only through redraw, which lenders can restrict, reprice or freeze, and which some
              have reduced with little notice.
            </li>
            <li>
              <strong className="text-ink">Tax, if the property is or becomes an investment.</strong>{" "}
              Interest is deductible according to the purpose of the borrowing. Redrawing from a
              loan is new borrowing, and the deduction follows what you spend it on, so redrawing
              for a holiday permanently contaminates part of the loan. Money moving in and out of
              an offset is your own cash and changes nothing. If there is any chance the home
              becomes a rental later, that difference is the whole ball game, and it is a
              conversation for your accountant as much as your broker.
            </li>
            <li>
              <strong className="text-ink">Cost.</strong> Offsets usually live inside a package
              with an annual fee. If you keep a small balance the fee can exceed the interest
              saved; if you keep a large one it is trivial. Work out the balance at which the fee
              breaks even before you pay for the feature.
            </li>
            <li>
              <strong className="text-ink">Discipline.</strong> Extra repayments are hard to
              undo, which is the point for some households and the problem for others. Offsets
              only work if the money actually stays there.
            </li>
          </ul>
          <p className="mt-6 text-lg leading-[1.4] text-ink/80">
            Partial offsets exist and are worth less than they sound: only part of the balance
            counts. If your current loan has an offset you are not using, or a package fee you
            are paying for features you never touch, that is precisely what the{" "}
            <TextLink href="/home-loan-health-check">home loan health check</TextLink> flags in
            two minutes.
          </p>
        </div>
      </section>

      <section className="py-20">
        <div className="container-x max-w-3xl">
          <h2 className="font-display text-[34px] font-normal leading-[1.15] tracking-tight text-ink sm:text-[44px]">
            Principal and interest, or interest only?
          </h2>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            Interest only means the balance does not move. It lowers the payment now and raises
            the payment later, because the same debt has to be repaid over a shorter remaining
            term. The table is the same {money(EXAMPLE_LOAN)} loan at the same illustrative{" "}
            {EXAMPLE_RATE}%, over a {EXAMPLE_TERM}-year total term.
          </p>
          <div className="mt-8">
            <DataTable
              caption="Principal and interest compared with a five year interest-only period on a $600,000 loan"
              head={["Structure", "First 5 years", "Years 6 to 30", "Total interest"]}
              rows={[
                [
                  "Principal and interest from day one",
                  `${money(monthly)}/mo`,
                  `${money(monthly)}/mo`,
                  money(baseInterest),
                ],
                [
                  `${IO_YEARS} years interest only, then P&I`,
                  `${money(io)}/mo`,
                  `${money(afterIo)}/mo`,
                  money(ioTotalInterest),
                ],
              ]}
              note="Same amortisation the calculator runs, at a constant illustrative rate. Interest-only periods are usually capped at 5 years for owner-occupiers and are reassessed before they can be extended."
            />
          </div>
          <p className="mt-6 text-lg leading-[1.4] text-ink/80">
            Read it as a trade, not a saving: {money(monthly - io)} a month of relief now, in
            exchange for {money(afterIo - monthly)} a month more later and{" "}
            {money(ioTotalInterest - baseInterest)} more interest overall. There are situations
            where that trade is right, and they are specific: an{" "}
            <TextLink href="/investment-home-loans">investment property</TextLink> where interest
            is deductible and you would rather direct spare cash at non-deductible home debt, a{" "}
            <TextLink href="/construction-loans-brisbane">construction loan</TextLink> during the
            build (interest only on drawn funds is standard), a genuine short-term cash-flow
            squeeze, or a bridging period. Choosing it to afford a house you otherwise cannot
            afford is how people meet the cliff at the end of the term with no plan.
          </p>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            Lenders price interest-only loans above principal and interest and assess them
            harder: serviceability is usually tested on the principal-and-interest repayment over
            the remaining term after the interest-only period ends, which shrinks{" "}
            <TextLink href="/borrowing-power-calculator">borrowing power</TextLink> rather than
            expanding it.
          </p>
        </div>
      </section>

      <section className="border-y border-ink/10 bg-neutral-50 py-20">
        <div className="container-x max-w-3xl">
          <h2 className="font-display text-[34px] font-normal leading-[1.15] tracking-tight text-ink sm:text-[44px]">
            The fortnightly trick, and the version that does nothing.
          </h2>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            There are two ways a lender can turn a monthly repayment into a fortnightly one, and
            only one of them saves you anything.
          </p>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            <strong className="text-ink">Half the monthly amount, 26 times a year.</strong> On the{" "}
            {money(EXAMPLE_LOAN)} example that is {money(monthly / 2)} a fortnight, which comes to{" "}
            {money(monthly * 13)} a year against {money(monthly * 12)} if you paid monthly. You
            have quietly made a thirteenth monthly payment. Over the full term it takes about{" "}
            {fortnightlyEffect.yearsSaved.toFixed(1)} years off the loan and saves roughly{" "}
            {money(fortnightlyEffect.interestSaved)} in interest, which is the same effect as
            adding {money(monthly / 12)} a month to the minimum.
          </p>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            <strong className="text-ink">A recalculated &quot;true fortnightly&quot; amount.</strong>{" "}
            Some lenders take the monthly figure, multiply by 12 and divide by 26, which on this
            loan is {money((monthly * 12) / 26)} a fortnight. That pays exactly the same total
            each year as monthly repayments and saves nothing at all. It is not a scam, it is
            just a different definition, and it is worth one question to your lender to find out
            which one you are on.
          </p>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            Two caveats. Weekly and fortnightly cycles only help while your loan calculates
            interest daily, which almost all Australian variable loans do. And fixed-rate loans
            usually cap what you can pay above the minimum each year, so check the cap before you
            change the cycle: if you are on a fixed rate, the{" "}
            <TextLink href="/refinancing-brisbane">roll-off date</TextLink> is the more valuable
            thing to have diarised.
          </p>
        </div>
      </section>

      <section className="py-20">
        <div className="container-x max-w-3xl">
          <h2 className="font-display text-[34px] font-normal leading-[1.15] tracking-tight text-ink sm:text-[44px]">
            What the repayment figure leaves out.
          </h2>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            The number above is principal and interest on the loan, and nothing else. The real
            monthly cost of owning also carries council rates, water, building insurance, body
            corporate if it applies, and maintenance. The real cost of the loan carries any
            monthly or annual package fee, and any{" "}
            <TextLink href="/lenders-mortgage-insurance-calculator">
              lenders mortgage insurance
            </TextLink>{" "}
            you capitalised, which is added to the balance and then charged interest for the life
            of the loan like everything else.
          </p>
          <p className="mt-4 text-lg leading-[1.4] text-ink/80">
            The calculation also assumes one rate for thirty years, which will not happen. That
            is what the stress test line in the tool is for: if the repayment at three
            percentage points higher is uncomfortable, the honest conclusion is to borrow less,
            not to hope. Work through{" "}
            <TextLink href="/borrowing-power-calculator">what a lender would lend you</TextLink>,
            then the{" "}
            <TextLink href="/stamp-duty-calculator-qld">duty and cash you need on the day</TextLink>,
            and keep the rest of the{" "}
            <TextLink href="/calculators">calculators and checks</TextLink> for the parts of the
            picture this page does not cover.
          </p>
        </div>
      </section>

      <FAQ
        title="Frequently asked questions."
        faqs={FAQS}
        related={[
          { label: "Borrowing power estimator", href: "/borrowing-power-calculator" },
          { label: "LMI calculator", href: "/lenders-mortgage-insurance-calculator" },
          { label: "Home loan health check", href: "/home-loan-health-check" },
          { label: "All calculators and checks", href: "/calculators" },
        ]}
      />
      <CtaBand
        heading="The repayment is maths. The rate is negotiation."
        intro="A broker compares your numbers across 35+ lenders. It's free, and the lender pays us."
        subject="Repayments calculator"
      />
    </main>
  );
}
